name: "Fetch Github Release Asset"
description: "Downloads an asset from a Github release"

inputs:
  repo:
    description: "org/repo to download from"
    required: false
    default: ""
  version:
    description: "version of the release to download from"
    required: false
    default: "latest"
  file:
    description: "name of the file in the release to download"
    required: true
  target:
    description: "name of the target file path"
    required: false
  token:
    description: "optional Personal Access Token to access external repository"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/fetch_github_asset.sh
      shell: bash

outputs:
  version:
    description: "The version of the release or tag"

branding:
  icon: "download-cloud"
  color: "orange"
